version: '3.8'

services:

  postgres-5432:
    image: postgres
    container_name: postgres-5432
    networks:
      - suncode-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres-5432" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: suncode-app
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - suncode-postgres
    depends_on:
      - postgres-5432
    env_file:
      - ./.env
    tty: true
    stdin_open: true

networks:
  suncode-postgres:
    driver: bridge