version: '3.8'

services:

  postgres-5432:
    image: postgres
    container_name: postgres-5432
    networks:
      - suncode-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - suncode-postgres
      - frontback
    depends_on:
      - postgres-5432
    env_file:
      - ./.env
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontback

networks:
  suncode-postgres:
    driver: bridge
  frontback:
    driver: bridge